// <auto-generated />
using System;
using System.Collections.Generic;
using Kynakee.Modules.Mcp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kynakee.Modules.Mcp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(McpDbContext))]
    [Migration("20261002190541_OptionalMcpQueryProject")]
    partial class OptionalMcpQueryProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("schema_mcp")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kynakee.Modules.Mcp.Domain.Aggregates.McpProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_until");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.PrimitiveCollection<List<string>>("_categories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("categories");

                    b.PrimitiveCollection<List<string>>("_geoRegions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("geo_regions");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_mcp_providers_tenant_id_id");

                    b.HasIndex("_categories")
                        .HasDatabaseName("idx_mcp_providers_category");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_categories"), "gin");

                    b.HasIndex("_geoRegions")
                        .HasDatabaseName("idx_mcp_providers_region");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_geoRegions"), "gin");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("idx_mcp_providers_tenant_status");

                    b.ToTable("mcp_providers", "schema_mcp", t =>
                        {
                            t.HasCheckConstraint("ck_mcp_providers_deleted", "is_deleted = (deleted_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_mcp_providers_failures", "consecutive_failures >= 0");

                            t.HasCheckConstraint("ck_mcp_providers_rating", "rating >= 0 AND rating <= 5");
                        });
                });

            modelBuilder.Entity("Kynakee.Modules.Mcp.Domain.Entities.McpQueryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalConceptId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("canonical_concept_id");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("component_type");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("CreditsCharged")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("credits_charged");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("FallbackSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fallback_source");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("QueriedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queried_at");

                    b.Property<decimal?>("ResponsePrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("response_price");

                    b.Property<string>("ResponseUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("response_unit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("TenantId", "ProjectId", "QueriedAt")
                        .HasDatabaseName("idx_mcp_query_logs_project");

                    b.HasIndex("TenantId", "ProviderId", "QueriedAt")
                        .HasDatabaseName("idx_mcp_query_logs_provider");

                    b.ToTable("mcp_query_logs", "schema_mcp", t =>
                        {
                            t.HasCheckConstraint("ck_mcp_query_logs_confidence", "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)");

                            t.HasCheckConstraint("ck_mcp_query_logs_credits", "credits_charged >= 0");

                            t.HasCheckConstraint("ck_mcp_query_logs_deleted", "is_deleted = (deleted_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_mcp_query_logs_duration", "duration_ms IS NULL OR duration_ms >= 0");

                            t.HasCheckConstraint("ck_mcp_query_logs_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Kynakee.Modules.Mcp.Domain.Entities.McpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CredentialSecretReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credential_secret_reference");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("idx_mcp_servers_endpoint")
                        .HasFilter("is_deleted = FALSE");

                    b.HasIndex("TenantId", "ProviderId")
                        .HasDatabaseName("idx_mcp_servers_provider");

                    b.ToTable("mcp_servers", "schema_mcp", t =>
                        {
                            t.HasCheckConstraint("ck_mcp_servers_deleted", "is_deleted = (deleted_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_mcp_servers_endpoint_https", "endpoint LIKE 'https://%'");
                        });
                });

            modelBuilder.Entity("Kynakee.Modules.Mcp.Domain.Entities.McpQueryLog", b =>
                {
                    b.HasOne("Kynakee.Modules.Mcp.Domain.Aggregates.McpProvider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kynakee.Modules.Mcp.Domain.Entities.McpServer", b =>
                {
                    b.HasOne("Kynakee.Modules.Mcp.Domain.Aggregates.McpProvider", null)
                        .WithMany("Servers")
                        .HasForeignKey("TenantId", "ProviderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kynakee.Modules.Mcp.Domain.Aggregates.McpProvider", b =>
                {
                    b.Navigation("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
