// <auto-generated />
using System;
using Kynakee.Modules.Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kynakee.Modules.Billing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260930233929_InitialBillingSchema")]
    partial class InitialBillingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("schema_billing")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kynakee.Modules.Billing.Domain.Aggregates.CreditAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId")
                        .HasName("ak_billing_credit_accounts_tenant_id");

                    b.ToTable("credit_accounts", "schema_billing", t =>
                        {
                            t.HasCheckConstraint("ck_billing_credit_accounts_deleted", "is_deleted = (deleted_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Kynakee.Modules.Billing.Domain.Entities.CreditLot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvailableCredits")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("available_credits");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<decimal>("RemainingCredits")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("ReservedCredits")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reserved_credits");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExpiresAt", "PurchasedAt")
                        .HasDatabaseName("ix_billing_credit_lots_tenant_expiry");

                    b.ToTable("credit_lots", "schema_billing", t =>
                        {
                            t.HasCheckConstraint("ck_billing_credit_lots_balance", "amount >= 0 AND available_credits >= 0 AND reserved_credits >= 0 AND amount = available_credits + reserved_credits");

                            t.HasCheckConstraint("ck_billing_credit_lots_deleted", "is_deleted = (deleted_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_billing_credit_lots_expiry", "expires_at >= purchased_at + interval '3 months'");
                        });
                });

            modelBuilder.Entity("Kynakee.Modules.Billing.Domain.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("Source")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_billing_credit_transactions_history");

                    b.HasIndex("TenantId", "OperationId", "CreatedAt")
                        .HasDatabaseName("ix_billing_credit_transactions_operation");

                    b.ToTable("credit_transactions", "schema_billing", t =>
                        {
                            t.HasCheckConstraint("ck_billing_credit_transactions_amount", "amount > 0");

                            t.HasCheckConstraint("ck_billing_credit_transactions_deleted", "is_deleted = (deleted_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_billing_credit_transactions_operation", "type = 'Recharged' OR operation_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Kynakee.Modules.Billing.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CreditsPerCycle")
                        .HasColumnType("integer")
                        .HasColumnName("credits_per_cycle");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cycle");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_subscriptions_stripe_id")
                        .HasFilter("stripe_subscription_id IS NOT NULL");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("subscriptions", "schema_billing", t =>
                        {
                            t.HasCheckConstraint("ck_billing_subscriptions_credits", "credits_per_cycle > 0");

                            t.HasCheckConstraint("ck_billing_subscriptions_deleted", "is_deleted = (deleted_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_billing_subscriptions_period", "current_period_end > current_period_start");
                        });
                });

            modelBuilder.Entity("Kynakee.Modules.Billing.Domain.Entities.CreditLot", b =>
                {
                    b.HasOne("Kynakee.Modules.Billing.Domain.Aggregates.CreditAccount", null)
                        .WithMany("CreditLots")
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kynakee.Modules.Billing.Domain.Entities.CreditTransaction", b =>
                {
                    b.HasOne("Kynakee.Modules.Billing.Domain.Aggregates.CreditAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Kynakee.Modules.Billing.Domain.ValueObjects.CreditReservationAllocation", "Allocations", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<Guid>("CreditLotId")
                                .HasColumnType("uuid")
                                .HasColumnName("credit_lot_id");

                            b1.Property<Guid>("credit_transaction_id")
                                .HasColumnType("uuid")
                                .HasColumnName("credit_transaction_id");

                            b1.HasKey("id");

                            b1.HasIndex("credit_transaction_id");

                            b1.ToTable("credit_transaction_allocations", "schema_billing");

                            b1.WithOwner()
                                .HasForeignKey("credit_transaction_id");
                        });

                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Kynakee.Modules.Billing.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Kynakee.Modules.Billing.Domain.Aggregates.CreditAccount", null)
                        .WithOne()
                        .HasForeignKey("Kynakee.Modules.Billing.Domain.Entities.Subscription", "TenantId")
                        .HasPrincipalKey("Kynakee.Modules.Billing.Domain.Aggregates.CreditAccount", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kynakee.Modules.Billing.Domain.Aggregates.CreditAccount", b =>
                {
                    b.Navigation("CreditLots");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
